api:
  environment: gitops
  telemetry:
    otlpTracesEndpoint: http://observability-tempo.observability.svc.cluster.local:4318/v1/traces
  image:
    repository: ghcr.io/varel183/opslab
    tag: 2d17d69a75db9ed67abe7231d4c9fae1ef3f6591
    pullPolicy: IfNotPresent
