nameOverride: ""
fullnameOverride: ""

api:
  replicaCount: 1
  image:
    repository: opslab-api
    tag: local
    pullPolicy: Never
  service:
    port: 8000
  environment: helm
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
  probes:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 5
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 10

postgresql:
  image:
    repository: postgres
    tag: 17-alpine
    pullPolicy: IfNotPresent
  auth:
    username: opslab
    password: change-me-for-real-environments
    database: opslab
  persistence:
    size: 1Gi
    storageClass: ""
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

