apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opslab.fullname" . }}-api
  labels:
    {{- include "opslab.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.api.environment | quote }}
  APP_NAME: "OpsLab Task API"

