apiVersion: v1
kind: Service
metadata:
  name: {{ include "opslab.fullname" . }}-postgres
  labels:
    {{- include "opslab.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "opslab.postgresSelectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres

