apiVersion: v1
kind: Service
metadata:
  name: opslab-api
  namespace: opslab
  labels:
    app: opslab-api
spec:
  selector:
    app: opslab-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opslab-api
  namespace: opslab
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: opslab-api
  template:
    metadata:
      labels:
        app: opslab-api
        app.kubernetes.io/part-of: opslab
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: api
          image: opslab-api:local
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opslab-db-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: postgresql+psycopg://opslab:$(POSTGRES_PASSWORD)@postgres:5432/opslab
          envFrom:
            - configMapRef:
                name: opslab-api-config
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
