apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app-config.yaml
  - postgres.yaml
  - api.yaml
  - monitoring/prometheus.yaml
  - monitoring/grafana.yaml

